language: java
jdk:
- openjdk8
after_success:
  - wget https://www.doggycraft.dk/travis/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://www.doggycraft.dk/travis/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
deploy:
  provider: releases
  api_key: e92d036e275958c01d1a342f577ca959540f8014
  file: Exams.jar
  skip_cleanup: true
  on:
    tags: true
