language: java
jdk:
- openjdk8
deploy:
  provider: releases
  api_key: e92d036e275958c01d1a342f577ca959540f8014
  file_glob: true
  file: "target/Exams-*.jar"
  skip_cleanup: true
  on:
    tags: true
sudo: false
addons:
  sonarcloud:
    organization: "dogonfire"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DogOnFire_Exams