name: Exams
main: com.dogonfire.exams.Exams
author: DogOnFire
version: ${project.version}
api-version: 1.14
load: POSTWORLD
description: Exams in Minecraft!
depend: [Vault]
website: https://dev.bukkit.org/projects/exams
commands:
  exams:
    description: Controls the Exams system
    usage: /exams
    aliases: exam
permissions:
    exams.*:
        description: Gives the Player access to control the Exams system
        default: false
        children:
            exams.student: true
            exams.place: false
            exams.list: true
            exams.info: true
            exams.reload: false
    exams.clean:
        description: Allows the Player to clean up expired student data
        default: false
    exams.student:
        description: Allows the Player to take exams
        default: true
    exams.place:
        description: Allows the Player to place exams
        default: false
    exams.reload:
        description: Allows the Player to reload configuration for the Exams system
        default: false
    exams.list:
        description: Allows the Player to see the list of exams
        default: true
    exams.info:
        description: Allows the Player to see details for an exam
        default: true
    exams.reset:
        description: Allows the Player to reset another players ExamTime
        default: false
    exams.nocooldown:
        description: Removes cooldown from the Player
        default: false